[package]
name = "rcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
sqlite = "0.24.0"
tonic = "0.7.1"
tonic-reflection = "0.4.0"
tokio = { version = "1.18.0", features = ["full"] }
prost = "0.10.1"
prost-types = "0.7.0"
chrono = "0.4"
futures = { version = "0.3.*" }
sodiumoxide = "0.2.7"

[build-dependencies]
tonic-build = "0.7.2"