use rcdp::{sql_client_client::SqlClientClient, AuthRequest};
use tonic_web_wasm_client::Client;
use simple_logger::SimpleLogger;
use log::debug;


mod rcdp;

#[tokio::main]
async fn main() {
    SimpleLogger::new().env().init().unwrap();

    let base_url = "http://localhost:9001"; // URL of the gRPC-web server
    let mut rcd = SqlClientClient::new(Client::new(base_url.to_string())); // `QueryClient` is the client generated by tonic

    let request = AuthRequest {
        user_name: "tester".to_string(),
        pw: "123456".to_string(),
        pw_hash: Vec::new(),
        token: Vec::new(),
        jwt: String::from(""),
        id: None,
    };

    let result = rcd.auth_for_token(request).await;
    debug!("{result:?}");
}
