debug = false
database_type = 1
backing_database_name = "rcd.db"
rcd_schema = "rcd"
client_service_addr_port = "[::1]:50051"
data_service_addr_port = "[::1]:50052"
admin_un = "tester"
admin_pw = "123456"
client_grpc_timeout_in_seconds = 5
data_grpc_timeout_in_seconds = 5